# Generated by Django 5.2.5 on 2025-08-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Sube .glb o .gltf', upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
