# Generated by Django 5.2.5 on 2025-10-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='audio',
            field=models.FileField(blank=True, help_text='Sube un MP3 (ideal) u OGG con la narración de este paso.', null=True, upload_to='audio/steps/'),
        ),
        migrations.AddField(
            model_name='step',
            name='tts_text',
            field=models.TextField(blank=True, help_text='(Opcional) Texto para TTS si no subes audio.'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
