# Generated by Django 5.2.5 on 2025-12-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_step_audio_step_tts_text_alter_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset3d',
            name='static_path',
            field=models.CharField(blank=True, help_text='Ruta en static. Ej: viewer/models/cierre.glb', max_length=255),
        ),
        migrations.AddField(
            model_name='step',
            name='audio_static_path',
            field=models.CharField(blank=True, help_text='Ruta en static. Ej: viewer/audio/paso1.mp3', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset3d',
            name='file',
            field=models.FileField(blank=True, help_text='(Opcional) Para local. En Render usa static_path.', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='audio',
            field=models.FileField(blank=True, help_text='(Opcional) Para local. En Render usa audio_static_path.', null=True, upload_to='audio/steps/'),
        ),
    ]
